apiVersion: v1
kind: Service
metadata:
  name: todo-backend
spec:
  type: NodePort
  selector:
    app: todo-backend
  ports:
  - port: 5000
    targetPort: 5000
    # nodePort: 30001  # (optional) specify if you want a fixed port
