apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
spec:
  type: NodePort
  selector:
    app: todo-frontend
  ports:
  - port: 80
    targetPort: 80
    # nodePort: 30002  # (optional) specify if you want a fixed port
