version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - todo_network
    restart: unless-stopped

  # Backend service
  backend:
    image: i222367/todo-backend:1.0
    container_name: todo-backend
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/TODO
      - PORT=5000
    networks:
      - todo_network
    restart: unless-stopped

  # Frontend service
  frontend:
    image: i222367/todo-frontend:1.0
    container_name: todo-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - todo_network
    restart: unless-stopped

# Networks
networks:
  todo_network:
    driver: bridge

# Volumes
volumes:
  mongodb_data:
    name: mongodb_data
