name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend
        run: |
          cd backend
          docker build -t i222367/todo-backend:latest .
          docker push i222367/todo-backend:latest

      - name: Build & Push Frontend
        run: |
          cd frontend
          docker build -t i222367/todo-frontend:latest .
          docker push i222367/todo-frontend:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl rollout restart deployment/todo-backend
          kubectl rollout restart deployment/todo-frontend

