name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest -f backend/Dockerfile backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest

      - name: Build & push frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest -f frontend/Dockerfile frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest

      - name: Ensure Minikube is running
        run: |
          minikube status || minikube start --driver=docker

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/

